# sistem opreasi yang digunakan
os:
  - linux
# bahasa yang digunakan
language: php
# menggunakan distory  yang di percaya
dist: trusty

# versi bahasa
php:
  - '7.1'
# service yang digunakan
services:
  - docker

# grouping task
jobs:
  include:
  # untuk melakuakan testing code
    - stage: "Tests"
      name: "Unit Test PHP"
      script:
      - travis_retry composer self-update
      - travis_retry composer install --prefer-source --no-interaction
      - cp .env.example .env
      - vendor/bin/phpunit tests/ExampleTest.php
    # untuk melakukan build image dan push ke docker hub
    - stage: "Build Docker Image"
      name: "Build Images Docker"
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t travis-ci-build-stages-demo .
      - docker images
      - docker tag travis-ci-build-stages-demo $DOCKER_USERNAME/belajar_git_4
      - docker push $DOCKER_USERNAME/belajar_git_4
